Repository ucsb-cs156-s23/proj-courses-s23-7pm-4, pull requests merged in 2023-06, with the labels that each got.

#26 bs/kt - course contrast
  frontend/src/index.css
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/SectionsOverTimeTableBase.js
  frontend/src/main/components/SectionsTableBase.js
Labels: 5

#41 bs - fixed bug with image not showing up on localhost
  src/main/java/edu/ucsb/cs156/courses/controllers/FrontendProxyController.java
Labels: 5, Merge Candidate-waiting for ci/cd

#44 kt - remove quarter from sections in course history table
  frontend/src/main/components/SectionsOverTimeTableBase.js
Labels: 5, Merge Candidate-waiting for ci/cd

#49 ss - added GradeData job and jobFactory files along with tests
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactory.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobTests.java
Labels: 10

#28 en/js added search for instructor
  frontend/src/App.js
  frontend/src/main/components/BasicCourseSearch/CourseInstructorSearchForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseInstructor/CourseInstructorIndexPage.js
  frontend/src/stories/components/BasicCourseSearch/CourseInstructorSearchForm.stories.js
  frontend/src/stories/pages/CourseInstructorIndexPage.stories.js
  frontend/src/tests/components/BasicCourseSearch/CourseInstructorSearchForm.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseInstructor/CourseInstructorIndexPage.test.js
Labels: 10

#60 js/en - fixed bug for default search
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
Labels: 5

#58 js/en-added controller and tests with query
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseInstructorController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseInstructorControllerTests.java
Labels: FIXME-Needs Peer CR

#51 rb - add CourseUtilities file for formatting course id
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/main/java/edu/ucsb/cs156/courses/utilities/CourseUtilities.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/utilities/CourseUtilitiesTests.java
Labels: Merge Candidate-waiting for ci/cd
